/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupTestIndexRouteImport } from './routes/setup-test/index'
import { Route as ComponentsComponentIdRouteImport } from './routes/components/$componentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTestIndexRoute = SetupTestIndexRouteImport.update({
  id: '/setup-test/',
  path: '/setup-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentIdRoute = ComponentsComponentIdRouteImport.update({
  id: '/components/$componentId',
  path: '/components/$componentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/setup-test/': typeof SetupTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/setup-test': typeof SetupTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/setup-test/': typeof SetupTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components/$componentId' | '/setup-test/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components/$componentId' | '/setup-test'
  id: '__root__' | '/' | '/components/$componentId' | '/setup-test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsComponentIdRoute: typeof ComponentsComponentIdRoute
  SetupTestIndexRoute: typeof SetupTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-test/': {
      id: '/setup-test/'
      path: '/setup-test'
      fullPath: '/setup-test/'
      preLoaderRoute: typeof SetupTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$componentId': {
      id: '/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof ComponentsComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsComponentIdRoute: ComponentsComponentIdRoute,
  SetupTestIndexRoute: SetupTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
